packages:
  - packages/*
  - integration_tests
  - demos/*
  - website

catalog:
  '@astrojs/mdx': ^4.3.13
  '@mdx-js/mdx': ^3.1.1
  '@types/markdown-it': ^14.1.2
  '@types/node': ^24.10.4
  astro: ^5.17.1
  devlop: ^1.1.0
  get-east-asian-width: ^1.4.0
  markdown-it: ^14.1.1
  micromark: ^4.0.2
  micromark-extension-gfm: ^3.0.0
  micromark-util-chunked: ^2.0.1
  micromark-util-resolve-all: ^2.0.1
  micromark-util-symbol: ^2.0.1
  micromark-util-types: ^2.0.2
  npm-run-all2: ^8.0.4
  rehype-stringify: ^10.0.1
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  tsdown: ^0.18.1
  unified: ^11.0.5

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - sharp

overrides:
  compression@1.8.0>on-headers: 1.1.0
  refractor@3.6.0>prismjs: ^1.30.0
  vite@5.4.21>esbuild: ^0.25.0

publicHoistPattern:
  - decode-named-character-reference
