packages:
  - packages/*
  - integration_tests
  - demos/*
  - website
onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - sharp
minimumReleaseAge: 1440
catalog:
  get-east-asian-width: ^1.4.0
  "@types/node": ^24.10.1
  markdown-it: ^14.1.0
  astro: ^5.15.8
  "@astrojs/mdx": ^4.3.10
  unified: ^11.0.5
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  rehype-stringify: ^10.0.1
  "@mdx-js/mdx": ^3.1.1
  devlop: ^1.1.0
  micromark: ^4.0.2
  micromark-extension-gfm: ^3.0.0
  micromark-util-chunked: ^2.0.1
  micromark-util-resolve-all: ^2.0.1
  micromark-util-symbol: ^2.0.1
  micromark-util-types: ^2.0.2
